//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffilizer.Data.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportURL
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public long URLId { get; set; }
        public System.DateTime ReportedDate { get; set; }
        public string ReportedBy { get; set; }
        public bool Resolved { get; set; }
        public bool Deleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual URL URL { get; set; }
    }
}
