//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffilizer.Data.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URL()
        {
            this.URLVisits = new HashSet<URLVisit>();
            this.ReportURLs = new HashSet<ReportURL>();
        }
    
        public long Id { get; set; }
        public string URLAddress { get; set; }
        public bool Status { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UserId { get; set; }
        public int Duration { get; set; }
        public bool AdminUrl { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URLVisit> URLVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportURL> ReportURLs { get; set; }
    }
}
